spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=hossein
spring.datasource.password=13851385
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

server.error.whitelabel.enabled=false

logging.level.web=trace
logging.level.sql=trace