spring.datasource.url=jdbc:postgresql://localhost:5434/user_service_db
spring.datasource.username=user_service_user
spring.datasource.password=UserAdmin
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

server.error.whitelabel.enabled=false

server.servlet.context-path=/api/v1/user
server.port=8081

spring.cache.cache-names=userCache